version: '3.4'

services:
  catalogdb: 
    image: mysql:8.0.33

  microcore.catalog.api:
    image: ${DOCKER_REGISTRY-}microcorecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/MicroCore.Catalog.API/Dockerfile

  basketdb:
    image: mysql:8.0.33

  basketredis:
    image: redis:alpine

  microcore.basket.api:
    image: ${DOCKER_REGISTRY-}microcorebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/MicroCore.Basket.Api/Dockerfile

  discountdb:
    image: mysql:8.0.33
  
  microcore.discount.grpc:
    image: ${DOCKER_REGISTRY-}microcorediscountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/MicroCore.Discount.Grpc/Dockerfile

  orderdb:
    image: mysql:8.0.33

  microcore.order.api:
    image: ${DOCKER_REGISTRY-}microcoreorderapi
    build:
      context: .
      dockerfile: src/Services/order/api/MicroCore.Order.API/Dockerfile

  paymentdb:
    image: mysql:8.0.33

  microcore.payment.api:
    image: ${DOCKER_REGISTRY-}microcorepaymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/MicroCore.Payment.Api/Dockerfile

  keycloakdb:
    image: mysql:8.0.33

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start

  rabbitmq:
    image: rabbitmq:3.13-management
 
  microcore.gateway:
    image: ${DOCKER_REGISTRY-}microcoregateway
    build:
      context: .
      dockerfile: src/Gateway/MicroCore.Gateway/Dockerfile

volumes:
  mysql_catalog:
  mysql_basket:
  redis_basket:
  mysql_discount: 
  mysql_order: 
  mysql_payment:
  mysql_keycloak_data:
  rabbitmq_data: