version: '3.4'

services:
  catalogdb: 
    image: postgres:latest

  microcore.catalog.api:
    image: ${DOCKER_REGISTRY-}microcorecatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/MicroCore.Catalog.API/Dockerfile

  basketdb:
    image: postgres:latest

  basketredis:
    image: redis:alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  paymentdb:
    image: postgres:latest

  microcore.basket.api:
    image: ${DOCKER_REGISTRY-}microcorebasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/MicroCore.Basket.Api/Dockerfile
  
  microcore.discount.grpc:
    image: ${DOCKER_REGISTRY-}microcorediscountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/MicroCore.Discount.Grpc/Dockerfile
  
  microcore.order.api:
    image: ${DOCKER_REGISTRY-}microcoreorderapi
    build:
      context: .
      dockerfile: src/Services/order/api/MicroCore.Order.API/Dockerfile

  microcore.payment.api:
    image: ${DOCKER_REGISTRY-}microcorepaymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/MicroCore.Payment.Api/Dockerfile

  keycloakdb:
    image: postgres:16.2

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start

  rabbitmq:
    image: rabbitmq:3.13-management

  
volumes:
  postgres_catalog:
  postgres_basket:
  redis_basket:
  sqlite_discount:
  mssql_order:
  postgres_payment:
  postgres_keycloak:
  rabbitmq_data:
