// <auto-generated />
using System;
using MicroCore.Basket.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroCore.Basket.Api.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20260524082849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MicroCore.Basket.Api.Models.Basket", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Coupon")
                        .HasColumnType("longtext");

                    b.Property<float?>("DiscountRate")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("MicroCore.Basket.Api.Models.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BasketUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceByApplyDiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BasketUserId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("MicroCore.Basket.Api.Models.BasketItem", b =>
                {
                    b.HasOne("MicroCore.Basket.Api.Models.Basket", null)
                        .WithMany("Items")
                        .HasForeignKey("BasketUserId");
                });

            modelBuilder.Entity("MicroCore.Basket.Api.Models.Basket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
